spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.port=8081

spring.datasource.url=jdbc:postgresql://ider-database.westeurope.cloudapp.azure.com:5433/h184536?currentSchema=poker
spring.datasource.username=h184536
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

server.error.include-stacktrace=always
server.error.include-message=always
